CREATE TABLE IF NOT EXISTS users (
    id UUID NOT NULL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS apis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    version VARCHAR(255) NOT NULL,
    base_path VARCHAR(255) NOT NULL,
    backend_url VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    owner_id UUID,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_apis_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS jobs (
    id UUID NOT NULL PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    request_payload OID NOT NULL,
    result OID,
    status VARCHAR(255) NOT NULL,
    submitted_by_id UUID,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_jobs_submitted_by FOREIGN KEY (submitted_by_id) REFERENCES users (id)
);
